/**
 * Generates docker-compose.yml with a randomized connected peer topology.
 * Run: npx tsx generate-compose.ts > docker-compose.yml
 */

interface AgentDef {
  id: string;
  port: number;
  model: string;
  tools: string[];
  system_prompt: string;
}

const agents: AgentDef[] = [
  // Research
  { id: "alpha",   port: 4201, model: "claude-opus-4-6",             tools: ["web_search"],      system_prompt: "You are a research specialist. You find information, synthesize sources, and deliver concise answers. You can delegate tasks to peers." },
  { id: "beta",    port: 4202, model: "claude-sonnet-4-6",           tools: ["web_search"],      system_prompt: "You are a research specialist. You find information, synthesize sources, and deliver concise answers. You can delegate tasks to peers." },
  { id: "gamma",   port: 4203, model: "claude-haiku-4-5-20251001",   tools: ["web_search"],      system_prompt: "You are a research specialist. You find information, synthesize sources, and deliver concise answers. You can delegate tasks to peers." },
  // Coders
  { id: "delta",   port: 4301, model: "claude-sonnet-4-6",           tools: ["code_exec"],       system_prompt: "You are a coding specialist. You write, debug, and review code. You can delegate tasks to peers." },
  { id: "epsilon", port: 4302, model: "claude-opus-4-6",             tools: ["code_exec"],       system_prompt: "You are a coding specialist. You write, debug, and review code. You can delegate tasks to peers." },
  { id: "zeta",    port: 4303, model: "claude-haiku-4-5-20251001",   tools: ["code_exec"],       system_prompt: "You are a coding specialist. You write, debug, and review code. You can delegate tasks to peers." },
  // Writers
  { id: "eta",     port: 4401, model: "claude-opus-4-6",             tools: ["write_document"],  system_prompt: "You are a writing specialist. You draft documents, reports, and prose. You can delegate tasks to peers." },
  { id: "theta",   port: 4402, model: "claude-sonnet-4-6",           tools: ["write_document"],  system_prompt: "You are a writing specialist. You draft documents, reports, and prose. You can delegate tasks to peers." },
  { id: "iota",    port: 4403, model: "claude-haiku-4-5-20251001",   tools: ["write_document"],  system_prompt: "You are a writing specialist. You draft documents, reports, and prose. You can delegate tasks to peers." },
];

const PEERS_PER_AGENT = 2;

// --- Random connected graph ---

function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

// Union-Find for connectivity check
class UnionFind {
  parent: number[];
  rank: number[];
  constructor(n: number) {
    this.parent = Array.from({ length: n }, (_, i) => i);
    this.rank = new Array(n).fill(0);
  }
  find(x: number): number {
    if (this.parent[x] !== x) this.parent[x] = this.find(this.parent[x]);
    return this.parent[x];
  }
  union(a: number, b: number) {
    const ra = this.find(a), rb = this.find(b);
    if (ra === rb) return;
    if (this.rank[ra] < this.rank[rb]) this.parent[ra] = rb;
    else if (this.rank[ra] > this.rank[rb]) this.parent[rb] = ra;
    else { this.parent[rb] = ra; this.rank[ra]++; }
  }
  connected(a: number, b: number) { return this.find(a) === this.find(b); }
}

function buildNetwork(n: number, peersPerAgent: number): Map<number, Set<number>> {
  const adj = new Map<number, Set<number>>();
  for (let i = 0; i < n; i++) adj.set(i, new Set());

  // Step 1: random spanning tree to guarantee connectivity
  const uf = new UnionFind(n);
  const order = shuffle(Array.from({ length: n }, (_, i) => i));
  for (let i = 1; i < order.length; i++) {
    const a = order[i];
    const b = order[Math.floor(Math.random() * i)];
    adj.get(a)!.add(b);
    adj.get(b)!.add(a);
    uf.union(a, b);
  }

  // Step 2: add random edges until each node has at least peersPerAgent peers
  for (let i = 0; i < n; i++) {
    const candidates = shuffle(Array.from({ length: n }, (_, j) => j).filter(j => j !== i && !adj.get(i)!.has(j)));
    for (const j of candidates) {
      if (adj.get(i)!.size >= peersPerAgent) break;
      adj.get(i)!.add(j);
      adj.get(j)!.add(i);
    }
  }

  return adj;
}

// --- Generate YAML ---

const network = buildNetwork(agents.length, PEERS_PER_AGENT);

let yaml = `# Auto-generated by generate-compose.ts — do not edit by hand
# Regenerate: npx tsx generate-compose.ts > docker-compose.yml

x-agent: &agent-base
  build: ./agent
  depends_on:
    event-server:
      condition: service_healthy
  volumes:
    - ~/.catallaxy/tokens.json:/root/.catallaxy/tokens.json:ro

services:
  event-server:
    build: ./event-server
    ports:
      - "4100:4100"
    environment:
      PORT: "4100"
    volumes:
      - event-data:/app/data
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:4100/health').then(r => { if (!r.ok) process.exit(1) })"]
      interval: 5s
      timeout: 3s
      retries: 3
`;

for (let i = 0; i < agents.length; i++) {
  const agent = agents[i];
  const peerIndices = Array.from(network.get(i)!);
  const peers = peerIndices.map(j => ({
    id: agents[j].id,
    url: `http://${agents[j].id}:${agents[j].port}`,
    description: "An agent",
  }));

  const config = {
    id: agent.id,
    port: agent.port,
    model: agent.model,
    tools: agent.tools,
    system_prompt: agent.system_prompt,
    peers,
    event_server_url: "http://event-server:4100",
  };

  yaml += `
  ${agent.id}:
    <<: *agent-base
    ports:
      - "${agent.port}:${agent.port}"
    environment:
      AGENT_CONFIG: >
        ${JSON.stringify(config)}
`;
}

// Control arm
const controlConfig = {
  id: "control",
  port: 4500,
  model: "claude-sonnet-4-6",
  tools: ["web_search", "code_exec", "write_document"],
  system_prompt: "You are a generalist assistant. You can research, code, and write. Complete tasks independently.",
  peers: [],
  event_server_url: "http://event-server:4100",
};

yaml += `
  control:
    <<: *agent-base
    ports:
      - "4500:4500"
    environment:
      AGENT_CONFIG: >
        ${JSON.stringify(controlConfig)}

volumes:
  event-data:
`;

console.log(yaml);

// Print topology to stderr for visibility
console.error("\n--- Peer topology ---");
for (let i = 0; i < agents.length; i++) {
  const peers = Array.from(network.get(i)!).map(j => agents[j].id);
  console.error(`  ${agents[i].id} -> ${peers.join(", ")}`);
}
console.error("");
